# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 22:04
from __future__ import unicode_literals

import app_data.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ella.core.cache.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20160203_1221'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('publishable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Publishable')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
            bases=('core.publishable',),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Slug')),
                ('order', models.IntegerField(verbose_name='Object order')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('text', models.TextField(blank=True)),
                ('app_data', app_data.fields.AppDataField(default=b'{}', editable=False)),
                ('gallery', ella.core.cache.fields.CachedForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ella_galleries.Gallery', verbose_name='Parent gallery')),
                ('photo', ella.core.cache.fields.CachedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Photo', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Gallery item',
                'verbose_name_plural': 'Gallery items',
            },
        ),
    ]
